apiVersion: v1
kind: ConfigMap
metadata:
  name: yolov8-service-config
  labels:
    app: yolov8-service
data:
  ENVIRONMENT: development
  LOG_LEVEL: debug
  ENGINE_URL: http://engine-service:8080
  # (the port must be the same as in the sample-service.service.yml and unused by other services)
  SERVICE_URL: http://yolov8-service-service:9696
